### ISSUE TITLE
segment report prev_nonzero index error

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#183]
This is problem is present in the segment report. It's avoided in customreports::detailed_segment_report
just with try, except:pass (i.e. not fixed but doesn't raise an error).

I've set as priority 1, but it is easily worked around by using the detailed report.

Traceback (most recent call last):
  File "C:\Users\Mark Torrance\Desktop\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\markwrite-0.2.2.11-py2.7.egg\markwrite\reports\__init__.py", line 332, in export
    for row in cls.datarows():
  File "C:\Users\Mark Torrance\Desktop\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\markwrite-0.2.2.11-py2.7.egg\markwrite\reports\segment.py", line 104, in datarows
    next_nonzero_ix = nonzero_pressure_ixs[np.searchsorted(nonzero_pressure_ixs, end_index, side='left')+1]
IndexError: index 9793 is out of bounds for axis 0 with size 9793
Traceback (most recent call last):
  File "C:\Users\Mark Torrance\Desktop\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\markwrite-0.2.2.11-py2.7.egg\markwrite\reports\__init__.py", line 332, in export
    for row in cls.datarows():
  File "C:\Users\Mark Torrance\Desktop\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\markwrite-0.2.2.11-py2.7.egg\markwrite\reports\segment.py", line 104, in datarows
    prev_penpress_time = pendata['time'][prev_nonzero_ix]
IndexError: index 9793 is out of bounds for axis 0 with size 9793
Press any key to continue . . .

**Comment by isolver** [comment]
I think this is fixed already?
